server:
  port: 9000

spring:
  application:
    name: acode-learn-auth
  datasource:
    url: jdbc:mysql://localhost:3306/acode_auth
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update